// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Wj-v1T0yHGGHjFW1kJgzG6CEpFUkhqg',
    appId: '1:778968890570:web:1dca63446448f79390c833',
    messagingSenderId: '778968890570',
    projectId: 'tiktok-jun-abc',
    authDomain: 'tiktok-jun-abc.firebaseapp.com',
    storageBucket: 'tiktok-jun-abc.appspot.com',
    measurementId: 'G-S32RKKZZDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSMOf5deTdIMz6ILddjIUpGfLNb0x1Lg',
    appId: '1:778968890570:android:7391a128c137177390c833',
    messagingSenderId: '778968890570',
    projectId: 'tiktok-jun-abc',
    storageBucket: 'tiktok-jun-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiMrGTy8dROX6y2jodxPSPIZ0nbrrh8gE',
    appId: '1:778968890570:ios:2bcedab06fe632ff90c833',
    messagingSenderId: '778968890570',
    projectId: 'tiktok-jun-abc',
    storageBucket: 'tiktok-jun-abc.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
